name: cyclic-synchronization-research-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - matplotlib=3.1.3
  - scipy=1.4.1
  - numpy=1.18.1
  - statsmodels=0.11.0
  - seaborn=0.10.0
  - peakutils=1.3.2
  - numba=0.48.0
  - networkx=2.4
  - tqdm=4.42.1
  - ipywidgets=7.5.1
  - scikit-learn=0.22.1
  - openpyxl=3.0.3
  - ffmpeg=4.2.2
  - pip:
    - -e ./code
